os:
  - osx
addons:
  chrome: stable
matrix:
  fast_finish: true

language:
  node_js

node_js:
  - '9'
  - '8'
  - '6'

before_script:
  - node --version
  - npm --version

script:
  - npm run ci                  # run linting and testing, generate coverage
  - npm install webpack@^3.0.0  # install webpack@3
  - npm run mocha               # run mocha tests against webpack@3, without coverage

after_success:
  npm run cover
