version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: install clipboard support
          command:
            sudo apt install xsel
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: npm run ci
          command: npm run ci
      - run:
          name: npm install webpack@^3.0.0
          command: npm install webpack@^3.0.0
      - run:
          name: npm run mocha
          command: npm run mocha
      - run:
          name: npm run cover
          command: npm run cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
