version: 2
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: circleci/node:9-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: install clipboard support
          command: |
            sudo apt install xsel
            sudo apt install xvfb
      - run:
          name: modify display support
          command:
            export DISPLAY=:99.0 && ls /etc/init.d
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: ls
          command: ls -asln && ls node_modules -asln
      - run:
          name: CI Tests
          command: npm run ci
      - run:
          name: Generate code coverage
          command: npm run cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
