version: 2
jobs:
  build:
    working_directory: /tmp/app
    docker:
      - image: circleci/node:9-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:9-stretch
    steps:
      - checkout
      - run:
          name: ls
          command: ls -asln && ls node_modules -asln
      - run:
          name: CI Tests
          command: npm run ci
      - run:
          name: Generate code coverage
          command: npm run cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
